name: Decode media b64 to JPEG
on:
  workflow_dispatch:
  push:
    paths:
      - staging/**
permissions:
  contents: write
jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decode and commit
        run: bash staging/decode.sh
